"""
Dictionary to collapse airports, clubs, colleges, grocery,
malls, entertainment, etc. individual venues into one venue.
"""

event_facil_addresses = {'2627 N HOLLYWOOD WAY':          'BOB HOPE',
                         '2500 N HOLLYWOOD WAY':          'BURBANK',
                         '700 WORLD WAY':                 'LAX',
                         '600 WORLD WAY':                 'LAX',
                         '400 WORLD WAY':                 'LAX',
                         '380 WORLD WAY':                 'LAX',
                         '300 WORLD WAY':                 'LAX',
                         '200 WORLD WAY':                 'LAX',
                         '100 WORLD WAY':                 'LAX',
                         '538 S FLOWER ST':               'CALIFORNIA CLUB',
                         '590 S BURLINGAME AVE':          'BRENTWOOD COUNTRY CLUB',
                         '545 S FIGUEROA ST':             'JONATHAN CLUB',
                         '1900 PICO BLVD':                'SANTA MONICA COLLEGE',
                         '1000 E VICTORIA ST':            'CSU DOMINGUEZ',
                         '901 E ALOSTA AVE':              'AZUZA PACIFIC UNIVERSITY',
                         '11110 E ALONDRA BLVD':          'CERRITOS COLLEGE',
                         '3607 TROUSDALE PKWY':           'USC',
                         '1 LMU DR #MS 8420':             'LMU',
                         '18111 NORDHOFF ST':             'CAL STATE NORTHRIDGE',
                         '5151 STATE UNIVERSITY DR':      'CAL STATE LA',
                         '24255 PACIFIC COAST HWY':       'PEPPEREDINE',
                         '240 S DIAMOND BAR BLVD':        'GROCERY',
                         '770 S GRAND AVE':               'WHOLE FOODS',
                         '27931 KELLY JOHNSON PKWY':      'WALMART',
                         '2725 HYPERION AVE':             'GELSONS',
                         '23381 MULHOLLAND DR':           'VONS',
                         '690 E HOLT AVE':                'CARDENAS',
                         '14049 VENTURA BLVD':            'RALPHS',
                         '18571 SOLEDAD CANYON RD':       'VALLARTA SUPERMARKET',
                         '345 E MAIN ST':                 '99 RANCH MARKET',
                         '1525 E AMAR RD':                'SEAFOOD CITY SUPERMARKET',
                         '910 LINCOLN BLVD':              'RALPHS',
                         '10861 WEYBURN AVE':             'RALPHS',
                         '11030 W JEFFERSON BLVD':        'PAVILLIONS',
                         '27095 MCBEAN PKWY':             'PAVILLIONS',
                         '2740 W OLYMPIC BLVD':           'HANNAM',
                         '2627 LINCOLN BLVD':             'ALBERTSONS',
                         '500 N SEPULVEDA BLVD':          'RALPHS',
                         '16550 SOLEDAD CANYON RD':       'VONS',
                         '4365 GLENCOE AVE':              'PAVILLIONS',
                         '21035 HAWTHORNE BLVD':          'SMART & FINAL',
                         '2520 GLENDALE BLVD':            'WHOLE FOODS',
                         '2825 S DIAMOND BAR BLVD':       'H MART',
                         '3830 W VERDUGO AVE':            'ALBERTSONS',
                         '4340 PACIFIC COAST HWY':        'SUPER H',
                         '9616 W PICO BLVD':              'RALPHS',
                         '1110 W ALAMEDA AVE':            'PAVILLIONS',
                         '12746 W JEFFERSON BLVD':        'WHOLE FOODS',
                         '260 S LA BREA AVE':             'RALPHS',
                         '745 W NAOMI AVE':               'VONS',
                         '9990 LONG BEACH BLVD':          'GROCERY',
                         '21080 GOLDEN SPRINGS DR':       'HANNAM',
                         '225 LINCOLN BLVD':              'WHOLE FOODS',
                         '3911 S FIGUEROA ST':            'COLISEUM - ENTERTAINMENT',
                         '111 RAGING WATERS DR':          'RAGING WATER LA',
                         '1201 S FIGUEROA ST':            'LA CONVENTION CENTER',
                         '5333 ZOO DR':                   'LA ZOO',
                         '135 N GRAND AVE':               'MUSIC CENTER',
                         '649 W JEFFERSON BLVD':          'SHRINE AUDITORIUM',
                         '1050 S HILL ST':                'BELASCO',
                         '800 W OLYMPIC BLVD STE A335':   'CLUB NOKIA',
                         '18400 AVALON BLVD STE 300':     'STUBHUB CENTER',
                         '2700 N VERMONT':                'GREEK THEATER',
                         '777 W CHICK HEARN CT':          'MICROSOFT THEATER',
                         '6360 W SUNSET BLVD':            'ARCLIGHT',
                         '6801 HOLLYWOOD BLVD':           'DOLBY',
                         '3400 S FIGUEROA ST':            'GALEN CENTER',
                         '3939 S FIGUEROA ST':            'BANC OF CALIFORNIA STADIUM',
                         '285 W HUNTINGTON DR':           'SANTA ANITA PARK',
                         '2301 N HIGHLAND AVE':           'HOLLYWOOD BOWL',
                         '1000 VIN SCULLY AVE':           'DODGER STADIUM',
                         '1000 ELYSIAN PARK AVE # 246':   'DODGER STADIUM',
                         '26101 MAGIC MOUNTAIN PKWY':     'SIX FLAGS MAGIC MOUNTAIN',
                         '1111 S FIGUEROA ST':            'STAPLES',
                         '2701 N SEPULVEDA BLVD':         'MAGNIN AUDITORIUM',
                         '1101 W MCKINLEY AVE':           'FAIRPLEX',
                         '6081 CENTER DR STE 201':        'CINEMARK',
                         '3900 W MANCHESTER BLVD':        'ARAMARK',
                         '6215 SUNSET BLVD':              'HOLLYWOOD PALLADIUM',
                         '380 SANTA MONICA PIER':         'PACIFIC PARK',
                         '800 W OLYMPIC BLVD':            'LA LIVE',
                         '9750 AIRPORT BLVD':             'FOUR POINTS',
                         '506 S GRAND AVE':               'BILTMORE',
                         '9200 W SUNSET BLVD':            'SOHO HOUSE',
                         '711 S HOPE ST':                 'SHERATON',
                         '21850 OXNARD ST':               'MARRIOTT',
                         '6121 SUNSET BLVD':              'NEUEHOUSE',
                         '9641 SUNSET BLVD':              'BEVERLY HILLS HOTEL',
                         '701 STONE CANYON RD':           'BEL AIR',
                         '929 S BROADWAY ST':             'ACE',
                         '900 W OLYMPIC BLVD':            'JW MARRIOTT HOTEL',
                         '9500 WILSHIRE BLVD':            'FOUR SEASONS',
                         '5855 W CENTURY BLVD':           'MARRIOTT',
                         '6225 W CENTURY BLVD':           'HYATT',
                         '3635 FASHION WAY':              'MARRIOTT',
                         '225 N CANON DR':                'MONTAGE',
                         '1020 N SAN VICENTE BLVD':       'LONDON',
                         '530 PICO BLVD':                 'LE MERIDIEN',
                         '888 BICYCLE CASINO DR':         'BICYCLE HOTEL CASINO',
                         '1700 OCEAN AVE':                'LOEWS HOTEL',
                         '9876 WILSHIRE BLVD':            'BEVERLY HILTON',
                         '2025 AVENUE OF THE STARS':      'HYATT REGENCY CENTURY PLAZA',
                         '930 HILGARD AVE':               'W HOTEL',
                         '431 W 7TH ST':                  'LAAC',
                         '648 S BROADWAY':                'CLIFTONS',
                         '6101 W CENTURY BLVD':           'SHERATON',
                         '3515 WILSHIRE BLVD':            'LINE HOTEL',
                         '9901 S LA CIENEGA BLVD':        'HOLIDAY INN',
                         '5711 W CENTURY BLVD':           'HILTON',
                         '1910 OCEAN FRONT WALK':         'HOTEL CASA DEL MAR',
                         '3883 W CENTURY BLVD':           'HOLLYWOOD PARK CASINO',
                         '1440 E IMPERIAL AVE':           'EMBASSY SUITES',
                         '6600 TOPANGA CANYON BLVD':      'WESTFIELD TOPANGA',
                         '9039 SUNSET BLVD':              '1 OAK',
                         '208 N RODEO DR':                '208 RODEO',
                         '1000 ELYSIAN PARK AVE':         'DODGER STADIUM'
                         }

# need to remove '929 BROADWAY ST'
# 2714 PECK RD, 11640 VICTORY BLVD, 11800 JEFFERSON BLVD, 330 S HOPE ST', 
# CONT. 18342 SOLEDAD CANYON RD, 2456 W WHITTIER BLVD,10202 WASHINGTON BLVD (sony), 
# CONT. 4000 WARNER BLVD, 5550 PEARBLOSSOM HWY, 3333 S HOOVER ST, 9765 SOMERSET BLVD 
# CONT '18347 COLIMA RD', '13755 FIJI WAY'- let it feed thru individ
# group by address and zip code